swagger: "2.0"
info:
  description: "Bank Argent API documentation (transaction page): contains all available API endpoints  in this codebase."
  version: "1.0.0"
  title: "Bank Argent API documentation"
  termsOfService: "http://swagger.io/terms/"
 
host: "localhost:3001"
basePath: "/api/v1"
schemes:
- "https"
- "http"
paths:
  /user/login:
    post:
      tags:
      - "User Module"
      summary: "Login"
      description: "API for Login"
      # operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Login Payload"
        required: true
        schema:
          $ref: "#/definitions/Login"
      responses:
        "200":
          description: "Login Successfully"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid fields"
        "404":
          description: "Internal Server Error"
 
 
  /user/signup:
    post:
      tags:
      - "User Module"
      summary: "Signup"
      description: "API for Signup"
      produces:
      - "application/json"
      parameters: 
      - in: "body"
        name: "body"
        description: "Signup Payload"
        required: true
        schema:
          $ref: "#/definitions/Signup"
      responses:
        "200":
          description: "Signup Successfully"
          schema:
            $ref: "#/definitions/Signup"
        "400":
          description: "Invalid fields"
        "404":
          description: "Internal Server Error"
 
  /user/logout:
    get:
      tags:
      - "User Module"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
          
  /user/profile:
    post:
      security:
      - Bearer: []
      tags:
      - "User Module"
      summary: "User Profile API"
      description: "API for fetching user profile"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Attach Bearer JWT token"
        required: true
        type: "string"
      responses:
        "200":
          description: "User profile retrieved successully"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid Fields"
        "404":
          description: "Internal Server Error"
    put:
      security:
      - Bearer: []
      tags:
      - "User Module"
      summary: "User Profile API"
      description: "API for updating a user profile"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Attach Bearer JWT token"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "Update user profile attributes"
        schema:
            $ref: "#/definitions/UserProfile"
        required: true
      responses:
        "200":
          description: "User profile retrieved successully"
          schema:
            $ref: "#/definitions/UserProfile"
        "400":
          description: "Invalid Fields"
        "404":
          description: "Internal Server Error"
          
  /user/transactions:
    get:
      tags:
        - "User Transactions"
      summary: "User transactions"
      description: "Shows user transactions of the month"
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      produces:
        - "application/json"
      responses:
        '200':
          description: "User transactions retrieved Successfully"
          schema:
            $ref: '#/definitions/UserTransaction'
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
    post:
      security:
        - Bearer: []
      tags:
        - "User Transactions"
      summary: "Update transactions information"
      description: "Modify the transactions information"
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "transaction payload"
          required: true
          schema:
            $ref: '#/definitions/TransactionPayload'
      produces:
        - "application/json"
      responses:
        '200':
          description: "Transaction's infos updated successfully"
          schema:
            $ref: '#/definitions/TransactionModification'
        '400':
          description: "Account id is required."
        '500':
          description: "Internal Server Error"
    
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    
definitions:
  User:
    properties:
      status:
        type: "integer"
      email:
        type: "string"
      id:
        type: "string"
  
  UserProfile:
    properties:
      firstname:
        type: "string"
      Lastname:
        type: "string"
  Login:
    properties:
      email:
        type: "string"
      password:
        type: "string"

  Signup:
    properties:
      email:
        type: "string"
      password:
        type: "string"
      firstname:
        type: "string"
      lastname: 
        type: "string"
  
  UserTransaction:
    properties:
      status:
        type: "integer"
      message:
        type: "string"
        example: "User transactions retrieved succesfully"
      body:
        type: "array"
        
  TransactionPayload:
    properties:
      transactionType:
        type: "string"
        description: "transaction type"

  TransactionModification:
    properties:
      status:
        type: "integer"
      message:
        type: "string"
        example: "User transaction updated succesfully"
      body:
        type: "array"

        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"